CargaFiles/Models/Productos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CargaFiles.Models
{
    public class Productos
    {
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Id { get; set; }
        public Usuarios usuarios { get; set; }

    }
}

CargaFiles/Controllers/ProductoController.cs
using CargaFiles.Logica;
using CargaFiles.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace CargaFiles.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Producto
        public ActionResult CrearProducto()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CrearProducto(Productos prod, HttpPostedFileBase Archivo)
        {
            //int a = prod.usuarios.Id;
           
            if (prod.Nombre == null || prod.Descripcion == null)
            {
                return View("Error", new { message = "Falla al registrarte" });

            }
            else if (prod.Nombre != null)
            {
                FormsAuthentication.SetAuthCookie(prod.ToString(), false);
                int a = (int)Session["IdUsuario"];
                Session["Usuario"] = prod.Nombre;
                Productos objeto = new LO_Usuario().CrearProduct(prod, a);
                Imagen(Archivo);
                ViewBag.Message = "User registered successfully!";
                return RedirectToAction("Index", "Principal");
            }

            //Productos objeto = new LO_Usuario().CrearProduct(prod,a);
            //ViewBag.Message = "User registered successfully!";
            return RedirectToAction("Index", "Principal");
        }

        [HttpPost]
        public void Imagen(HttpPostedFileBase Archivo)
        {
            if (Archivo == null)
            {
                // return View("Error", new { message = "Falla al registrarte" });
                // No se puede retornar una vista desde un método void, se puede generar un error o registrar una excepción
                throw new Exception("Falla al registrarte");
            }
            else
            {
                FormsAuthentication.SetAuthCookie(Archivo.ToString(), false);
                int a = (int)Session["IdUsuario"];
                string name = Path.GetFileName(Archivo.FileName);
                MemoryStream ms = new MemoryStream();
                Archivo.InputStream.CopyTo(ms);
                byte[] data = ms.ToArray();
                Productos prod = new LO_Usuario().GetProductos(a);
                Session["IdProducto"] = prod.IdProducto;
                int b = (int)Session["IdProducto"];
                new LO_Usuario().SubirImagen(b, data, name);
                // ViewBag.Message = "User registered successfully!";
                // No se puede usar ViewBag desde un método void
            }
        }
    }
}

CargaFiles/Views/Producto/CrearProducto.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreaProducto</title>
    @Styles.Render("~/Content/css")
</head>
    <body>
        <div class="container">

            <div class="row">


                <div class="col-sm-8 col-sm-offset-2">


                    <form action="@Url.Action("CrearProducto","Producto")" class="bg-info" style="padding:10px" method="post" enctype="multipart/form-data"">

                        <div class="form-group">
                            <label>Nombres Producto</label>
                            <input class="form-control" type="text" name="Nombre" />
                            <label>Descripcion</label>
                            <input class="form-control" type="text" name="Descripcion" />
                            <label>Archivo:</label>
                            <input class="form-control" type="file" name="Archivo"  />
                            
                        </div>
                        <button type="submit" class="btn btn-success">Guardar</button>

                    </form>
                </div>
            </div>
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
    </body>
</html>